#!/bin/sh

BASE="$(pwd)"
SELF="$(realpath $0)"
ROOT="$(dirname $SELF)"

export PATH="$ROOT/bin:$PATH:/sbin:/usr/sbin"
export CLISH_PAGER="less -XFe"
export EDITOR="vim"
export PYTHONPATH="$ROOT:/usr/local/stow/klish/lib/python3.7/site-packages"
export CLISH_PATH="$ROOT/xml-main::$ROOT/xml-basic:$ROOT/xml-generic:$ROOT/xml-linux:$ROOT/xml-debian"

# run clish
exec $WRAP clish $@
